# Generated by Django 5.1.5 on 2025-01-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(upload_to='activities/'),
        ),
    ]
